
services:
  web:
    build: .
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anderground
      - POSTGRES_DB=my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
